### ISSUE TITLE
Cache property

### ISSUE THREAD

**Issue by jpouderoux** [georstat/react-native-image-cache#10]
Hi,

Could it be possible to add a `cache` property, similar to the one provided by the stock Image component?

In particular, I would like to be able to set the `only-if-cached` option in some cases - meaning if the image
is not in the cache then it won't try to download it. Otherwise, I could simulate it by myself but only if the
`CacheManager` would provide a method to check if a image is in the cache or not.

Thanks for help and this useful library!

**Comment by geobako** [comment]
You can check the new release [V1.3.0](https://github.com/georstat/react-native-image-cache/releases/tag/v1.3.0). We added the `CacheManager.isImageCached`  method.

**Comment by jpouderoux** [comment]
Works great, thanks a lot!
