### ISSUE TITLE
Loading source is not constrained to size

### ISSUE THREAD

**Issue by perry-mitchell** [georstat/react-native-image-cache#11]
I'm using this library to present website icons in my app, which work very nicely. I'm having an issue with the `loadingSource` image, however, which is _not_ constrained to the same size as the website icon. You can see that it's much larger (perhaps original size) during load:

![Kapture 2021-10-29 at 23 01 31](https://user-images.githubusercontent.com/3869469/139495344-a66df905-0e2e-4e00-89c4-d136b97f113e.gif)

Here's how I'm using it:

```jsx
<CachedImage
    loadingSource={ICON_TYPES[type]}
    source={`${ICON_LOOKUP}${encodeURIComponent(domain)}`}
    style={{ height: size, width: size }}
/>
```

`ICON_TYPES[type]` is just a local imported `png` image.

**Comment by geobako** [comment]
Hi @perry-mitchell

Could you try the loadingImageStyle prop and let us know?

**Comment by perry-mitchell** [comment]
@geobako Thanks for the response! Actually I just fixed this by applying a style to the surrounding view (overflow: hidden), which has fixed it. I didn't get a chance to try `loadingImageStyle` yet, but if I remember I'll give it a go and will report back.

**Comment by perry-mitchell** [comment]
Just want to say that this library is working amazingly well, I'm really impressed. Great job!
