### ISSUE TITLE
no way to know if an image finished loading

### ISSUE THREAD

**Issue by rbozan** [georstat/react-native-image-cache#15]
no way to know if an image finished loading

in normal React Native you have `onLoad` and `onLoadEnd`, here you don't have it.

**Comment by efstathiosntonas** [comment]
Hi @rbozan, can you please give us a use case about these two props? It will help us understand on how to expose them.

**Comment by rbozan** [comment]
Basically we have a custom animation for the images that we'd like to keep, however because we don't know when the image has finished loading we can't start the custom animation.

**Comment by geobako** [comment]
Hey @rbozan , we added onLoad and onLoadEnd props in the new version 1.4.0. I will close this issue for now but feel free to tell us if everything is working as expected
