### ISSUE TITLE
expo failing on build react-native-file-access:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by likon416** [georstat/react-native-image-cache#23]
expo run:android is failing to build with error:
> Task :react-native-file-access:compileDebugKotlin FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

is it local or eas build the same error. using expo SDK 44.0.6

**Comment by efstathiosntonas** [comment]
Hi @likon416, we’ve never tested it on expo and we truly don’t know if it’s compatible. Does iOS build or you haven’t tested it?

**Comment by likon416** [comment]
Hi @efstathiosntonas thanks for the swift replay.

iOS builds fine. it's just android that is failing.

**Comment by efstathiosntonas** [comment]
As far as I know `react-native-file-access` might now be compatible with expo, at least on Android. 

Either open an issue on that module’s repo or create one new expo project with our module only and see if it builds. 

Before doing all the above, can you run `./gradlew clean` just to be sure there are no remnants left on Android folders?

**Comment by efstathiosntonas** [comment]
There are some solutions here too about this issue on react-native: https://stackoverflow.com/questions/67135414/w-detected-multiple-kotlin-daemon-sessions-at-build-kotlin-sessions

**Comment by likon416** [comment]
Thanks @efstathiosntonas 

gradle clean didn't help, as the project on expo that I work on is not bare I can't use all that stuff you are normally using. 
decided I will go with a different cache plugin that is compatible with expo managed workflow.

Thanks!

**Comment by efstathiosntonas** [comment]
@likon416 I think you should open an issue on `react-native-file-access`, still.

@alpha0010

**Comment by efstathiosntonas** [comment]
it seems `react-native-file-access` uses [kotlin `1.6.10`](https://github.com/alpha0010/react-native-file-access/blob/master/android/gradle.properties), what kotlin version expo is using?

**Comment by efstathiosntonas** [comment]
can you do something like this on expo?  https://stackoverflow.com/a/71374918/2195000

sorry that i've turned the conversation into chat 😄

**Comment by likon416** [comment]
@efstathiosntonas I can't do that as I'm on a managed workflow which means you don't touch any ios or android files it's all generated, configured and managed by expo scripts.

**Comment by efstathiosntonas** [comment]
oh I see, never used expo before so my knowledge is limited.

**Comment by efstathiosntonas** [comment]
can you try this: `expo prebuild --clean`? I've google searched about the issue and it seems that other devs have the same issue with other libraries eg. gesture-handler but I couldn't spot a fix other than trying to clean the project, sorry.

**Comment by likon416** [comment]
that didn't help. But I moved to use expo-cached-image and that works fine.

**Comment by alpha0010** [comment]
You can select which version of Kotlin `react-native-file-access` uses by specifying in your `build.gradle`.
```gradle
buildscript {
    ext {
        // buildToolsVersion = 'xx.xx.xx'
        // [...]
        kotlinVersion = '1.6.10'
        kotlinCoroutinesVersion = '1.6.0'
    }
// [...]
```

Should clean build after changing version numbers.

**Comment by alpha0010** [comment]
Ah, missed that.  Strange though that it appears Expo is using the same version https://github.com/expo/expo/blob/main/android/build.gradle#L11 ?

**Comment by efstathiosntonas** [comment]
I have a feeling that the issue is reanimated 2.5.0 even though the error point to react-native-file-access. There’s an issue open about it: https://github.com/software-mansion/react-native-reanimated/issues/3097

I think these 2 modules in conjunction with expo don’t play well.

@likon416 can you try using v1.6.0 of this module instead of 2.0.1? That version doesn’t use reanimated 2.
