### ISSUE TITLE
Support pre-fetching?

### ISSUE THREAD

**Issue by martinmidtsund** [georstat/react-native-image-cache#24]
Hi,

Are you planning on supporting pre-fetching of images in this library, or is this possible now in some way?

Thank you. :)

**Comment by efstathiosntonas** [comment]
Hi @martinmidtsund, can you give us a small example of what you’re trying to achieve?

**Comment by martinmidtsund** [comment]
@efstathiosntonas  Thanks for your quick reply!

I would like to prefetch/preload an image by URL before the screen that will show that image to the user are navigated to. Sometimes the image will not have the time to finish before navigation, but it would have a head start so the image would load even faster (or so the user would believe).

It's like the functionality already in React Native's Image-component (https://reactnative.dev/docs/image#prefetch) , or in the Fast Image library (https://github.com/DylanVann/react-native-fast-image#fastimagepreload-source--void)

**Comment by efstathiosntonas** [comment]
@martinmidtsund @geobako let’s do this, @geobako do you have an ETA?

**Comment by geobako** [comment]
Hi guys, I think it will be ready in two weeks as we are on holiday right now

**Comment by martinmidtsund** [comment]
Wow, great news guys, will be exciting to test! Have a good vacation :)

**Comment by efstathiosntonas** [comment]
Hi @martinmidtsund, please update to `2.1.0`, we've added prefetch. More info on [README](https://github.com/georstat/react-native-image-cache/blob/main/README.md#prefetch-images-and-store-them-in-cache)

**Comment by martinmidtsund** [comment]
Hi @efstathiosntonas

Cool, I'll test it as soon as I can!  🤩
