### ISSUE TITLE
How to implement this with ImageBackground?

### ISSUE THREAD

**Issue by putuoka** [georstat/react-native-image-cache#26]
i have tried replace my imagebackground tag with this but give me an error. because i have view inside imagebackground for displaying text above image

**Comment by efstathiosntonas** [comment]
Hi @putuoka, what error are you getting?

**Comment by efstathiosntonas** [comment]
@putuoka this module won’t accept any chlidren so it’s normal that you get an error. Closing this since it’s not a bug.

**Comment by megacherry** [comment]
Hi @efstathiosntonas,

is it possible to ehance this library for this use case?

best regards

**Comment by nathantew14** [comment]
@megacherry simply place the image and what you want displayed in front of it, inside a view. Then set the content in front of the image to have `position: "absolute"`
