### ISSUE TITLE
Invariant Violation: Module AppRegistry error

### ISSUE THREAD

**Issue by scaraux** [georstat/react-native-image-cache#27]
```
    "react-native-file-access": "^2.4.1",
    "react-native": "^0.67.3",
    "react-native-reanimated": "2.4.1",
    "@georstat/react-native-image-cache": "^2.1.0",
```

I am getting the following error while adding to my `App.tsx`

```
CacheManager.config = {
  baseDir: `${Dirs.CacheDir}/images_cache/`,
  blurRadius: 15,
  cacheLimit: 0,
  sourceAnimationDuration: 1000,
  thumbnailAnimationDuration: 1000,
};
```

```
TypeError: undefined is not a function, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
```

and also:

```
 ERROR  TypeError: undefined is not a function, js engine: hermes
```

**Comment by efstathiosntonas** [comment]
Hi @scaraux, have you tried this? https://github.com/georstat/react-native-image-cache/issues/22

**Comment by scaraux** [comment]
@efstathiosntonas yes I have! Also reanimated merged their PR to fix that issue so I doubt its that

**Comment by efstathiosntonas** [comment]
That’s weird. Can you delete your node_modules folder, yarn.lock or package-lock.json and then reinstall everything?

you should also start react native start with `—clear-cache` just to be sure.

**Comment by scaraux** [comment]
Tried it all, it still fails. By the way, worth mentioned that it fails also with nothing in my `App.tsx` and just adding the image like so:

```
      <CachedImage
        source="https://via.placeholder.com/3500x3500"
        style={{ height: 350, width: 150 }}
        thumbnailSource="https://via.placeholder.com/350x150"
      />
```

<img width="418" alt="CleanShot 2022-05-22 at 17 10 48@2x" src="https://user-images.githubusercontent.com/26309761/169702152-7e5a2f8a-e01c-419a-b505-e7c0ab625730.png">

**Comment by efstathiosntonas** [comment]
Can you create a repo with a minimum reproduction and share it here to take a look? 

The screenshot above indicates that the module is not installed.

**Comment by scaraux** [comment]
Sure I can do that!
And yes I ran `pod install` although this lib doesn't have native code so I don't think it would do anything. Its more for the file-access lib

**Comment by scaraux** [comment]
@efstathiosntonas here it is a barebone js react-native project
https://github.com/scaraux/RNIC_Issue/tree/master

**Comment by efstathiosntonas** [comment]
@scaraux took a quick look at package.json and you’re missing `react-native-reanimated`. This module requires it. Are you 100% sure that you have installed it on the project that gives you issues?

**Comment by scaraux** [comment]
I thought that regardless you guys import it in your package.json. Yes I am 100% sure we use it all over across the app.
I just added it to my above project for you to see, doesn't change anything.

**Comment by scaraux** [comment]
Okay it seems to be working now that I added reanimated... I don't have the same version of reanimated on our project. I will investigate.

**Comment by efstathiosntonas** [comment]
@scaraux glad you figured it out, closing this and thanks for your patience in this one.

**Comment by scaraux** [comment]
Thank you for assisting me and for the fast replies. Appreciate it 👍🏻

**Comment by scaraux** [comment]
@efstathiosntonas I will reply here in case people run through the same issue.

I was able to fix it on my main project by bumping reanimated to `2.4.1 -> 2.8.0`

Suggestion: It wasn't clear for me that both libs have to be installed (I thought that they would install automatically since your package requires it). You should probably add the `yarn add reanimated` & `yarn add react-native-file-access` in the installation section.

Thanks

**Comment by efstathiosntonas** [comment]
You can use whatever version of `react-native-reanimated` you want as long as it aligns with the version this module is using, in your case you had 2.4.1 while this package requires 2.6.0, this mismatch caused the issue , that’s why I’ve proposed to use resolutions https://github.com/georstat/react-native-image-cache/issues/22. 

I understand that this is an aggressive approach, we will loosen the requirement of using a specific version of reanimated as this causes troubles like yours so I think it might not be necessary to add instructions on README, we’ll see.
