### ISSUE TITLE
Style problems

### ISSUE THREAD

**Issue by Baer05** [georstat/react-native-image-cache#36]
There seems to be a problem with the style: if I pass style={{ borderRadius: 20 }} nothing happens. I would expect the image to have rounded corners now. Am I right that this is currently not possible or am I doing something wrong?

**Comment by efstathiosntonas** [comment]
Hi @Baer05, if you add `overflow: “hidden”` does it round the image?

**Comment by Baer05** [comment]
Hi @efstathiosntonas, thanks for the super fast response... with overflow:hidden it works as requested. Thank you for your help

**Comment by efstathiosntonas** [comment]
You're welcome @Baer05, glad you sorted it out. The overflow thing is a quirk or react-native Image component when using radius on images, it's been around for ages 😄

**Comment by DeepBlueDevOps** [comment]
Ran in to the same issue ... This worked great - thanks!

**Comment by Thijmen** [comment]
Unfortunately, this doesn't seem to work for me. Has something changed around this subject?

**Comment by efstathiosntonas** [comment]
Hi @Thijmen, nothing has changed 🤷‍♂️

Can you share your code?

**Comment by Thijmen** [comment]
Hi @efstathiosntonas, sure;

```
 <CachedImage
        source={'https://placehold.co/600x400/000/FFFFFF.png'}
        style={{ height: 200, width: 200, marginLeft: 50, borderRadius: 20, overflow: 'hidden' }}
      />
      <Image
        source={{ uri: 'https://placehold.co/600x400/000/FFFFFF.png' }}
        style={{
          height: 200,
          width: 200,
          marginLeft: 50,
          borderRadius: 20,
          overflow: 'hidden'
        }}
      />
```

Above code results in:

<img width="355" alt="image" src="https://github.com/georstat/react-native-image-cache/assets/383903/f871e03f-fb07-4342-83e0-989dc2ec4f3d">

**Comment by efstathiosntonas** [comment]
Can you wrap the CachedImage with a View and apply overflow:"hidden"?

**Comment by Thijmen** [comment]
Following code leads to this screen:

```
  <View>
      <View style={{ overflow: 'hidden' }}>
        <CachedImage
          source={'https://placehold.co/600x400/000/FFFFFF.png'}
          style={{ height: 200, width: 200, marginLeft: 50, borderRadius: 20, overflow: 'hidden' }}
        />
      </View>

      <Image
        source={{ uri: 'https://placehold.co/600x400/000/FFFFFF.png' }}
        style={{
          height: 200,
          width: 200,
          marginLeft: 50,
          borderRadius: 20,
          overflow: 'hidden'
        }}
      />
    </View>
```


<img width="284" alt="image" src="https://github.com/georstat/react-native-image-cache/assets/383903/88cebc00-4a53-4b96-a20f-013d5492294a">

**Comment by efstathiosntonas** [comment]
if you also give borderRadius:20 on View?

**Comment by Thijmen** [comment]
Leads to the same result:
```
import { Image, View } from 'react-native'
import { CachedImage } from '@georstat/react-native-image-cache'

export const TestScreen = () => {
  return (
    <View>
      <View style={{ overflow: 'hidden', borderRadius: 20 }}>
        <CachedImage
          source={'https://placehold.co/600x400/000/FFFFFF.png'}
          style={{ height: 200, width: 200, marginLeft: 50, borderRadius: 20, overflow: 'hidden' }}
        />
      </View>

      <Image
        source={{ uri: 'https://placehold.co/600x400/000/FFFFFF.png' }}
        style={{
          height: 200,
          width: 200,
          marginLeft: 50,
          borderRadius: 20,
          overflow: 'hidden'
        }}
      />
    </View>
  )
}

```

**Comment by Thijmen** [comment]
@efstathiosntonas Am I doing something wrong? Are you able to reproduce?

**Comment by Thijmen** [comment]
Can we re-open this issue? Currently using react-native `0.72.6` and version `3.1.0` of this package.

**Comment by pierre-softimpact** [comment]
I had this problem but it was fixed when I set the resizeMode of the CachedImage to "cover".

**Comment by Thijmen** [comment]
Yes, that seems to work for me too @pierre-softimpact! Thanks!
