### ISSUE TITLE
blurRadius not available for loaded images

### ISSUE THREAD

**Issue by maxcan** [georstat/react-native-image-cache#41]
Great library but the way it uses `blurRadius` makes it impossible for me to use it.  I sometimes need to blur a fully loaded image.  But, `blurRadius` is "captured" here https://github.com/georstat/react-native-image-cache/blob/fe0ce4aee6b39a7e307f801b372cc711a9e3b5e0/src/CachedImage.tsx#L166 to use for thumbnail loading.  It would be great if `blurRadius` were separated into `thumbnailBlurRadius` for loading and `blurRadius` that would behave like the react native image prop.  If there's interest, I could make and submit a PR for this.

**Comment by efstathiosntonas** [comment]
Hi Max, thanks for the suggestions, we’re open to PR’s, we want to make this module to fit all possible usages and keep fellow devs happy 😃. 

I believe the `blurRadius` should default to `0` and let the devs set a higher value if needed and make `thumbnailBlurRadius` `15` (as it is now). What do you think?

**Comment by maxcan** [comment]
Sounds reasonable.  I have this working on a fork.  I'll submit a WIP PR so that you can see the changes and let me know anything else you'd want me to change (changelog, etc)
