### ISSUE TITLE
Expo support for expo-file-system

### ISSUE THREAD

**Issue by ScreamZ** [georstat/react-native-image-cache#43]
Does this support expo (https://docs.expo.dev/versions/latest/sdk/filesystem/) for auto-pruning could be nice ?

I'm looking for a drop replacement for https://github.com/DylanVann/react-native-fast-image

**Comment by efstathiosntonas** [comment]
@ScreamZ we must create a separate package for expo, @geobako what do you think? 

In the meantime you can patch the package (with `patch-package`) and use the equivalent methods of expo’s filesystem module. Ofcourse it’s a hack but it won’t be hard to make the changes.

**Comment by ScreamZ** [comment]
Alright, I take notes :-) Thanks

Also found https://github.com/echowaves/expo-cached-image which look similar,

Very curious about how we could achieve same behavior without making two libraries.
 I had a similar issue on one library I made that have different implementation on browser and react native. I guess this could be nice to add some kind of abstraction and let the user choose at runtime ?
