### ISSUE TITLE
Using with a managed expo app

### ISSUE THREAD

**Issue by kickbk** [georstat/react-native-image-cache#5]
Hi @geobako,
Found your library while searching for a hybrid solution that can offer the benefits of William’s library and fast-image. looks like I'm not the only one 🙂
Do you think there’s a way to make it usable in a Managed Expo project? Perhaps `expo-file-system` could be used instead of `react-native-file-access`?

**Comment by geobako** [comment]
Hi @kickbk,

Unfortunately, we do not plan on supporting expo. I think the best solution would be for someone to fork it and make it expo compatible.
