### ISSUE TITLE
Support for WebP

### ISSUE THREAD

**Issue by ShivamJoker** [georstat/react-native-image-cache#55]
Hey it would be great if we could support for webp images as well.

**Comment by efstathiosntonas** [comment]
Hi @ShivamJoker, the lib supports webp, we add the extension `.jpg` if we can’t identify the filename extension from the url. 

Did you experienced any issues with webp?

**Comment by ShivamJoker** [comment]
Hey sorry, actually I missed putting height and width so I couldn't see the images.

Also I added fresco in the build.gradle.
Not sure if we need it.

**Comment by efstathiosntonas** [comment]
No worries! Yes you need fresco-webp and react-native-webp otherwise images won’t load.
