### ISSUE TITLE
v1.6.0 question

### ISSUE THREAD

**Issue by omer921** [georstat/react-native-image-cache#65]
Currently using v1.6.0 because we have a dependency on reanimated v1.13.2. If an image is not in the cache how do we set it into the cache? I was not able to find documentation for this.

**Comment by efstathiosntonas** [comment]
Hi @omer921, the image will land in your cache dir when it fetches it for the first time from your url. Everything is happening automagickaly, you don't have to do anything. 

Are you encountering any issues?
