### ISSUE TITLE
Thumbnails required?

### ISSUE THREAD

**Issue by xerdnew** [georstat/react-native-image-cache#66]
I have been looking for some time now after a package that can replace react-native-fast-image. This looks really good but i see in your documentations that thumbnails is required? Is it not possible to use it just like a Image replacement with the caching functionality?

There is not alot of maintained image packages out there right now that has immutable caching like this and is maintained.

Best regards.

**Comment by geobako** [comment]
@xerdnew please try using it without thumbnail as in the example. We will also change the docs
