### ISSUE TITLE
 Error: [Reanimated] `valueUnpacker` is not a worklet, js engine: hermes

### ISSUE THREAD

**Issue by sunetic** [georstat/react-native-image-cache#67]
Is there anyone knowns how to resovle this error ?

I had to use react-native-reanimated@3.5.1 ,maybe that is the problem ?

**Comment by efstathiosntonas** [comment]
Hi @sunzhaoyang, reanimated@3.5.1 is unstable, please try again when this PR is released: https://github.com/software-mansion/react-native-reanimated/pull/5087

**Comment by efstathiosntonas** [comment]
hey @sunzhaoyang, reanimated@3.5.2 is out, please install it and try again

**Comment by tab** [comment]
@efstathiosntonas I got the same error message with react-native-reanimated@3.5.2

```
"@georstat/react-native-image-cache": "^3.1.0",
"react-native-file-access": "^3.0.4",
"react-native-reanimated": "^3.5.2",

"react": "18.2.0",
"react-native": "0.72.4",
```

**Comment by efstathiosntonas** [comment]
@tab can you try `yarn start —reset-cache`?

Unfortunately this was a reanimated issue that is fixed on 3.5.2, on our apps we do not get this bug.

**Comment by Salmahana** [comment]
I am having the same error using reanimated ^3.5.2 , still no clue how to solve it

**Comment by efstathiosntonas** [comment]
@Salmahana have you tried `yarn start —reset-cache`?

**Comment by sumitthakur1** [comment]
Hello, I have the same issue.I installed the latest version by `npm install react-native-reanimated@latest ` and added 
` "react-native-reanimated": "^3.5.2",` is installed
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
}; 
```
in  babel.config.js and clear cache also but the same issue is there. Any help?

**Comment by efstathiosntonas** [comment]
Hey folks, please create an issue on the reanimated repo, this is not an issue with this lib, we don’t use something weird or complex on our code with reanimated, if there’s a bug it’s on their side, not ours.

**Comment by oloomoses** [comment]
Had the same issue while upgrading RN app. I found this [solution on stackoveflow](https://stackoverflow.com/questions/67130651/reanimated-2-failed-to-create-a-worklet-maybe-you-forgot-to-add-reanimateds-ba) to be working.

**Comment by IsabelleCCC** [comment]
I had the same issue and I fixed it with a version downgrade:

``` npm install react-native-reanimated@3.4.2 react-native-gesture-handler@2.12.1 ```

And editing the babel.config.js file:

``` 
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
}; 
```

**Comment by shamaskaramat** [comment]
How i can get back my console?

**Comment by efstathiosntonas** [comment]
@shamaskaramat Hi,  what do you mean by getting back your console?

**Comment by Elvixx10** [comment]
Solutions:

add to babel.config.js

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
  ],
};

and

npx react-native start --reset-cache 

👍

**Comment by Nauj-Montes** [comment]
What fixed it for me was:

1. `npx expo install react-native-gesture-handler react-native-reanimated`
2. Adding the before mentioned line `plugins: ['react-native-reanimated/plugin'],` to the Babel.config.js file.
3. Then clearing the Metro Bundler cache with `yarn start --reset-cache`

**Comment by chuyihuang** [comment]
> What fixed it for me was:
> 
> 1. `npx expo install react-native-gesture-handler react-native-reanimated`
> 2. Adding the before mentioned line `plugins: ['react-native-reanimated/plugin'],` to the Babel.config.js file.
> 3. Then clearing the Metro Bundler cache with `yarn start --reset-cache`

it's working! BTW i am using `"react": "18.2.0", "react-native-router-flux": "^4.3.1", "react-native-reanimated": "^3.5.4", "react-native-gesture-handler": "^2.13.1",`

**Comment by yosoyjavieruiz** [comment]
Modifique mi archivo babel.config.js

module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};

**Comment by Sagargajul41** [comment]
> I had the same issue and I fixed it with a version downgrade:
> 
> `npm install react-native-reanimated@3.4.2 react-native-gesture-handler@2.12.1`
> 
> And editing the babel.config.js file:
> 
> ```
> module.exports = {
>   presets: ['module:metro-react-native-babel-preset'],
>   plugins: ['react-native-reanimated/plugin'],
> }; 
> ```

This solution worked for me. Thanks

**Comment by dhruv7911** [comment]
> 2\. plugins: ['react-native-reanimated/plugin']

Thank you 
It works for expo

**Comment by trucuit** [comment]
> I had the same issue and I fixed it with a version downgrade:
> 
> `npm install react-native-reanimated@3.4.2 react-native-gesture-handler@2.12.1`
> 
> And editing the babel.config.js file:
> 
> ```
> module.exports = {
>   presets: ['module:metro-react-native-babel-preset'],
>   plugins: ['react-native-reanimated/plugin'],
> }; 
> ```

it works for me
