### ISSUE TITLE
Error when caching images.

### ISSUE THREAD

**Issue by BtMwanza** [georstat/react-native-image-cache#7]
I followed the instructions to setup the caching, but when the Home screen with the images mounts, I get an error saying "RNFileAccess.fetch got 2 arguments, expected 3".  I added the config in my App.js file and the CachedImage component in the Home screen.

**Comment by efstathiosntonas** [comment]
Hi @BtMwanza, please use `react-native-file-access` version `1.6.1`. We will update the package to reflect the changes made on `1.7.x` version.

**Comment by BtMwanza** [comment]
It works. Thanks

**Comment by efstathiosntonas** [comment]
@BtMwanza we've updated the package to include 1.7.1, just fyi
