### ISSUE TITLE
Delete an entry and loaded again

### ISSUE THREAD

**Issue by dandresfg** [georstat/react-native-image-cache#9]
Great library, is very usefull.

I have a version of profile pictures in my db, when i change it, i delete the entries, so i go back and reload the list (a list of users) and the same file is downloaded again... Not the actual file, is just the same i deleted it.

Its always the same URL for every user, so, the version of profile pic gives me a number to storage in the app, when the number changes i delete the entry cuz i need to download the new file (its just the same url but the file is already changed, thats the part who doesnt work)

**Comment by efstathiosntonas** [comment]
Hi @dandresfg, this module caches the image based on filename hashing so using the same uri every time won’t work out of the box. 

What you could do is to manually delete the file from cache so it will re-download it. 

Example from readme: https://github.com/georstat/react-native-image-cache#remove-single-cache-entry

find a sweet spot in the app to remove the file from cache, eg after a successful upload of the new image or before.

hope this helps you our!

**Comment by dandresfg** [comment]
```javascript 
static async removeCacheEntry(entry: string): Promise<void> {
    try {
      const file = await getCacheEntry(entry);
      await FileSystem.unlink(file.path);
      console.log(await getCacheEntry(entry))
    } catch (e) {
      throw new Error('error while clearing image from cache');
    }
  }
```

Take a look, the console.log gives me ` {"exists": false, "path": "/data/user/0/com.appmovil/cache/images/f007bdaebfd8f4e4d85ad131af20edc5b85a2183.jpg", "tmpPath": "/data/user/0/com.appmovil/cache/images/f007bdaebfd8f4e4d85ad131af20edc5b85a2183-12.jpg"}`

Cuz the **exists: false** means is deleted... When i downloaded again (try to search the same user, at this point i checked with another platform if the image changes and it does) gives me the same old file (deleted one)

**Comment by efstathiosntonas** [comment]
@dandresfg this is happening on both Platforms?

**Comment by dandresfg** [comment]
I figure it out the problem, but i cannot find a good solution... I'm going to make a deep explanation down below...

So, im showing an image from my user in his profile (in the same form he can edit his information)
```javascript
        <TouchableOpacity>
          {file ? (
            file.path.includes('odontosys') ? (
                <CachedImage
                  source={file.path}
                  loadingImageComponent={() => (<PlaceHolderImage width={120} height={120} />)}
                />
            ) : (
              <Image source={{uri: file.path}} />
            )
          ) : (
            <MaterialCommunityIcons name="image" size={30} color="#bdbdbd" />
          )}
        </TouchableOpacity>
```

_______
I put a setTimeout to delete the image 3 seconds after (not necessary, the backend's response it's made after the image is changed)
_______

So, after this i delete the image, im pretty sure i deleted it (i did many reviews) and if i dont go back to the profile and review the same image in the S3 (AWS) i can see the new image. So i wrote this to make sure im downloading the image again

```javascript
  private async download(
    path: string,
    tmpPath: string
  ): Promise<string | undefined> {
    const { source, options } = this;
    if (source != null) {
      console.log('Downloading: ', source)
      // ... the same code
  }
```

I can see the log, but here is the problem, is the same old file (not the new one). No matter how much longer i wait until get into the app, im always gettin the same old file. So i was wondering a lot of things, i dont know exactly how to fix this... But i dont know if the temp path have something to do with

Its like a cache in the download manager (im not sure enough)

**Comment by dandresfg** [comment]
So i worked deep in the library... I found a solution, add the version in the url like http://myurl/5.jpgversion10

and inside the app split('version')... So when the url changes i can download a new image with other source path... And it works.

**Comment by efstathiosntonas** [comment]
@dandresfg glad you found a solution, I believe your use case is rare, keeping always the same file name in images is not common, the main idea behind removing a single cache entry is to clear up cache space.

I think we should investigate this further to eliminate the possibility this being a module issue.

 Can you please console.log (while using emulator, not real device) the full path of the image before and after uploading a new one and navigate to that folder **in your local file system** and open the image file before and after the upload? If the image is the same then there should be something wrong in the module. 

If the image is not the same, what you could do is to add a `key` on the image component and force it to re-render after upload, something like:

```tsx

const [imageKey, setImageKey] = useState<number>(0)

const uploadLogic = () => {
  // upload stuff
 // when upload finishes
setImageKey(imageKey + 1)
}

<CachedImage key={imageKey} {...props} />

```
